apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io

spec:
  project: no-sync
  source:
    chart: longhorn
    repoURL: https://charts.longhorn.io
    targetRevision: 1.3.0

    helm:
      values: |
        service:
          ui:
            type: ClusterIP
          manager:
            type: ClusterIP

        persistence:
          defaultClass: true
          defaultFsType: ext4
          defaultClassReplicaCount: 1
          reclaimPolicy: Retain
          recurringJobSelector:
            enable: false
            jobList: []
          backingImage:
            enable: false

        csi:
          kubeletRootDir: ~
          attacherReplicaCount: 1
          provisionerReplicaCount: 1
          resizerReplicaCount: 1
          snapshotterReplicaCount: 1

        defaultSettings:
          backupTarget: ~
          backupTargetCredentialSecret: ~
          allowRecurringJobWhileVolumeDetached: ~
          createDefaultDiskLabeledNodes: ~
          defaultDataPath: ~
          defaultDataLocality: ~
          replicaAutoBalance: ~
          storageOverProvisioningPercentage: 50%
          storageMinimalAvailablePercentage: ~
          upgradeChecker: ~
          defaultReplicaCount: 1
          backupstorePollInterval: ~
          taintToleration: ~
          systemManagedComponentsNodeSelector: ~
          autoSalvage: ~
          autoDeletePodWhenVolumeDetachedUnexpectedly: ~
          disableSchedulingOnCordonedNode: ~
          nodeDownPodDeletionPolicy: ~
          allowNodeDrainWithLastHealthyReplica: ~
          mkfsExt4Parameters: ~
          disableReplicaRebuild: ~
          replicaReplenishmentWaitInterval: ~
          concurrentReplicaRebuildPerNodeLimit: ~
          disableRevisionCounter: ~
          systemManagedPodsImagePullPolicy: ~
          allowVolumeCreationWithDegradedAvailability: ~
          autoCleanupSystemGeneratedSnapshot: ~
          concurrentAutomaticEngineUpgradePerNodeLimit: ~
          backingImageCleanupWaitInterval: ~
          backingImageRecoveryWaitInterval: ~
          guaranteedEngineManagerCPU: ~
          guaranteedReplicaManagerCPU: ~

        resources: 
          limits:
           memory: 256Mi
          requests:
           cpu: 50m
           memory: 128Mi

        ingress:
          enabled: true
          host: longhorn.cloud.feddema.dev
          tls: true
          tlsSecret: longhorn-tls
          annotations:
            nginx.ingress.kubernetes.io/auth-url: "https://longhorn.cloud.feddema.dev/oauth2/auth"
            nginx.ingress.kubernetes.io/auth-signin: "https://longhorn.cloud.feddema.dev/oauth2/start?rd=$escaped_request_uri"

        enablePSP: false

  destination:
    server: https://kubernetes.default.svc
    namespace: longhorn-system

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 5
        maxDuration: 10m
