apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: oauth-prometheus
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io

spec:
  project: no-sync
  source:
    chart: oauth2-proxy
    repoURL: https://oauth2-proxy.github.io/manifests
    targetRevision: 6.3.0
    helm:
      values: |
        config:
          existingSecret: prometheus-oauth-credentials
          configFile: |-
            email_domains = [ "*" ]
            upstreams = [ "file:///dev/null" ]
            provider = "keycloak-oidc"
            oidc_issuer_url = "https://auth.cloud.feddema.dev/realms/master"
            redirect_url = "https://prometheus.cloud.feddema.dev/oauth2/callback"

        serviceAccount:
          enabled: true

        ingress:
          enabled: true
          path: /oauth2
          annotations:
            external-dns.alpha.kubernetes.io/hostname: prometheus.cloud.feddema.dev
            external-dns.alpha.kubernetes.io/ttl: "120"
            ingress.kubernetes.io/rewrite-target: /
            cert-manager.io/cluster-issuer: letsencrypt
          hosts:
            - prometheus.cloud.feddema.dev
          tls:
            - secretName: prometheus-tls
              hosts:
                - prometheus.cloud.feddema.dev

        resources:
          limits:
            memory: 100Mi
          requests:
            cpu: 30m
            memory: 50Mi

        proxyVarsAsSecrets: true

        securityContext:
          enabled: false
          runAsNonRoot: true
          allowPrivilegeEscalation: false
          runAsUser: 2000

        replicaCount: 1

        podDisruptionBudget:
          enabled: false

        httpScheme: http

        sessionStorage:
          type: redis
          redis:
            clientType: "standalone"
            password: secret

        redis:
          enabled: true
          architecture: standalone
          auth:
            enabled: true
            password: secret

        checkDeprecation: true

        metrics:
          enabled: false

  destination:
    server: https://kubernetes.default.svc
    namespace: prometheus

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 5
        maxDuration: 10m
