apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io

spec:
  project: always-sync
  source:
    chart: prometheus
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 19.0.1

    helm:
      values: |
        alertmanager:
          enabled: true
          useClusterRole: true
          baseURL: "https://alert.cloud.feddema.dev"
          replicaCount: 1

          persistence:
            enabled: true
            size: 8Gi

          resources:
            limits:
              memory: 64Mi
            requests:
              cpu: 10m
              memory: 32Mi
        
        kube-state-metrics:
          enabled: false
        
        prometheus-node-exporter:
          enabled: false
        
        configmapReload:
          prometheus:
            enabled: false
        
        server:
          enableServiceLinks: true

          baseURL: "https://prometheus.cloud.feddema.dev"

          configPath: /etc/config/prometheus.yml

          global:
            scrape_interval: 1m
            scrape_timeout: 10s
            evaluation_interval: 1m

          ingress:
            enabled: true

            annotations:
              nginx.ingress.kubernetes.io/auth-url: "https://$host/oauth2/auth"
              nginx.ingress.kubernetes.io/auth-signin: "https://$host/oauth2/start?rd=$escaped_request_uri"
              external-dns.alpha.kubernetes.io/hostname: prometheus.cloud.feddema.dev
              external-dns.alpha.kubernetes.io/ttl: "120"
              cert-manager.io/cluster-issuer: letsencrypt

            hosts:
              - prometheus.cloud.feddema.dev

            tls:
              - secretName: prometheus-tls
                hosts:
                  - prometheus.cloud.feddema.dev

          persistentVolume:
            enabled: true
            mountPath: /data
            size: 100Gi

          replicaCount: 1

          resources:
            limits:
              memory: 512Mi
            requests:
              cpu: 100m
              memory: 512Mi

          retention: "15d"

        prometheus-pushgateway:
          enabled: false

  destination:
    server: https://kubernetes.default.svc
    namespace: prometheus

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 5
        maxDuration: 10m

