apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-credentials
  namespace: default
spec:
  encryptedData:
    password: AgCIkfp3VGUEuqrNJrWPqfj2KrkdBrnBIBT/WSyyy70VQXUbh8CbUuD/uJbe9DyZHISQ/MaqZztQruaDWSGHrMdLuyeuNWDzlG9ZivYkvvCaHVkyRdt256FMnHBi03IZqiFD+F+d1w3O4prLP3zK3+ojch4f72TYC2z+Yy3fj14a6Ox/EH2ZQOamPg4dc0puIUahE826x0lOjsE+kxeAGRBUB4E/zS2AexHZGei7TkwtjcZTcLAltyJsiISGm7BrseY1KqkoyRWlL3ut9nacyGrVOznSHLWT99PhA6Y6TyqmGfpuz/SU3yHwWHjfyHfKG+26uGfGACSTnDqfxC5kGL1UwIoh6hrliQcpDw5LIM95oJaon8frdEBswhT1zaJoztQTdOIUttbLRcXkGrlnI6yIP7OrWL+7TRGHX4jTZxhuvfvHPxhNG5J5MV/PKTFDfx30H84gV46Lsll5JhRnJzck8k/kLxRNhtRjPt4k73wnnLqSYELhQbBQbhqk6n1M8xjkPVtk+7oju9X99HwFNTq9eoc/iadvBhOp8Ryo7Wa7mtOzx9jQAWhXFqyyx4Elb8i2Rs4S8nypG2zxNEynhm0Q5CWJLk6SNdGUPj0GD7qFlW6Zz+I3p3MEm08fe4bwWo3K453AZijJapHLFFyARSd2y49zFB8KoGj8j7xp52at1juEh3YAnQcDL4TtzZN7thzhkjO2V1O6GLL2vH4QMRbawrNJV/aQNMCLsm2j+qLq0w==
    username: AgCulr7CRCASimCKxxj3vO/9l3yBht8ni4rHr0dy8UxfJm1mO4/IbrCAI4QK9kk7V3m41GNU28c6qyjdcw603ptwb3mP2Ckn546z0SY08T53QPXqWsW4wpWf/LwxHv2h1TyoxYkf0oi7JDg68JYiuB7Af4LjT4shgnvzFcO381QTH1OuL+AkUFHOaPX8shr8tQMSzS8dWI9K+nZ1uZM5PTC87Snh6rPvi4jRFeqr03KI1Nh5EOvhEslqTPABb/7jD6bhNJm2m8g8eyqBNlcj9R5JAUIjg+wygBEi2dPQKUij5lXKgxmSUvtoXYMGeXFodcYq6muOwwQBGC4Rnc1vDKB+h3VzrTUhwkR3tHQOZBThrdIt+29KdieELDz+TVPaIpXVrfnvZg/cFMNDdandy/Z4zv7/KxFTG66v88MdCf4NEQPueNW2pIbowSbx2I+jqCt57hONB6zqGz/s4nB7jzaIfm0HtqpIG5H623oRRwIIDquqYWperskjt5LpVAeUe8w2s2iv0k63eTZM0VKZ3lFXKUY6ST3kAiVpl/Sox6y94t6s8hlVhwtFiU/Qy4yIhsi38NuxUm7v0glkGrQJ8U43DwKJDnIKlSluircSqTyjtztHZfF3+rjgiKHmGzovbCi6D10dLq0GvOuSfm7ApKS/clUIzLJlczrZnEx2GdMcOQ8gitjfJAysm/g62hgwkFkmyS9rlkHVgS+sHLN8LSBeMCMI/smu5cd3i5gZA0CK6Q==
  template:
    metadata:
      name: grafana-credentials
      namespace: default
    type: Opaque

