apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: backstage
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io

spec:
  project: no-sync
  source:
    chart: backstage
    repoURL: https://backstage.github.io/charts
    targetRevision: 

    helm:
      values: |

  destination:
    server: https://kubernetes.default.svc
    namespace: backstage

  revisionHistoryLimit: 2
  syncPolicy:
    syncOptions:
    - ServerSideApply=true
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 5
        maxDuration: 10m

