apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloud-gitops-dev
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: no-sync
  source:
    repoURL: https://github.com/Hize-bv/gitops.git
    targetRevision: HEAD
    path: ''

  destination:
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 5
        maxDuration: 10m
