apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: argocd-secret
  namespace: argocd
spec:
  encryptedData:
    oidc.keycloak.clientSecret: AgBOzQaFgJZ5hEpF+345Y98swq3r3Ihy5LLVPYqWnUW5gOIm8LaSnYQ7sPdGoiiesb1SUa/HjyTIMlFqIjHvxv3mmtDAGmW9txmnNJOsG/5ue5L/eb4PCn5F1wH+i+sd00YxIoRu7XD4RHhwJc4n3u/XrgVFnHjtRNLBW57cZXUsmNNbJ69MKovwo4Ew1VFndQslGaKj3+9hYv7KBoZoS2SJJOt2/F6lZzPoz3ni3DXQozu+Poia8OmTyO2xjS5r1vjsSDfXrTLpwbU9erAyq2FuZCxvVb58ICjqv44tDNlRiT3SRNhHEda0zDFSVjXD0Pw/H0YTyzcvgkU81RlmXkQ/c6D24EVTdeupGFXg5wNL07ppGCAwjUXh094PQcxXrvxhOfTr6vhnF/lUBnmUKROQkfEepTzOUwcmn3ruvpRBqPULyghqrg3pr9vRIG5tY5ER7o8NIMO5LEzDjRhzGi4O0Rjk/tOfRrnaEG1RDjFhJKGQyFmOH0Q4HWigEZ/4/VohrYXSVNlVZAO4ApSb4yfyAwZLuMwbUsDtCQ2bjbdd/YiHPM+M+17z3rU3kH+pqiogQ0fnVlb0BarIIe2vi5e4LKLAcyX+dfehzsJ1u1XH/k69iE07OPf77RdAwHEH4l3j8karelsUwhdzTNdrZp4FvoCG0SIVomFIhy7CtCrXMu8JFBIyN9kIw9rgE98+GdukqVfBgPFxinbaaTJ01smM3ma9y1yOsOzmu3w8/2aGIA==
  template:
    metadata:
      labels:
        app.kubernetes.io/name: argocd-secret
        app.kubernetes.io/part-of: argocd
      name: argocd-secret
      namespace: argocd

