apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: argocd-secret
  namespace: argocd
spec:
  encryptedData:
    server.secretkey: AgComay4SAQWmHoD6x8QK3+qpV/TSAStD1861PTZRxUhFh3Ik6lIWnfjX8NSgYjaAlVOAlbzAA1kKWoSgVnCIXtWTHNRcDcAGI3DAH0Ptz6kgXjLJHt/Ob7rYZ207FVXCqmMQVEW12uczlYCn03eDMZ5xC1XhCK8SaS4mFYi3x1b8Re5EYBWYrq0L0DB8ZSbGg1vNfddMLjqUOXlTtMqhDi2TZhIoi0eWG4HqDqgSaCZMddfDj8gHdGRc7AP8/YRTuC0bqvW4b3CkIZ/WGdEWMhdq3XuWw9iWTwLe1rPXnfSXGC/+r5qbj1rUVe6IctifGw37E/PFrfcobr6yI28lRst04DzbZoaY7nCbTeIfvtddxn/6oVCOjeFFEmV6wkGINhBmc/5jGTACg+q4PeTGFhS9oBCOAniottb5rCcSOteVeU/QcSw0K/qTrtky7t7Z43VsUiP88H2SrZxmq0mgzP2DKxhhOpb8ieY0XLi9Ta0GBN0h4wDgoDZCSpp0GRU5PoVR6ZH7vgHPEaeMN1QzouZ40cGjEqMjXiCUOWfVaXmPHlFcmZiaNq8+i4lcH3ywwpCZUh9Oexn6sFbZvvttfr4ua4UEA4bV4VnMLURWPKZR+9QHQdrt5AmEeF82zbjWbcvBVlIKdJxDsdbJcvmCNNv2LMLUEjZyMklHTsEG4NEt31v0dzCWvS5dEBKuxe+0GqPd73yWzrYAvjhoxGr6dNuTPIAZrK0RWCCuo0wjIzeqjpH1OWbrxZVY6r6//gReTpW8D3zYhbnt0gCN353rgub
    oidc.keycloak.clientSecret: AgBOzQaFgJZ5hEpF+345Y98swq3r3Ihy5LLVPYqWnUW5gOIm8LaSnYQ7sPdGoiiesb1SUa/HjyTIMlFqIjHvxv3mmtDAGmW9txmnNJOsG/5ue5L/eb4PCn5F1wH+i+sd00YxIoRu7XD4RHhwJc4n3u/XrgVFnHjtRNLBW57cZXUsmNNbJ69MKovwo4Ew1VFndQslGaKj3+9hYv7KBoZoS2SJJOt2/F6lZzPoz3ni3DXQozu+Poia8OmTyO2xjS5r1vjsSDfXrTLpwbU9erAyq2FuZCxvVb58ICjqv44tDNlRiT3SRNhHEda0zDFSVjXD0Pw/H0YTyzcvgkU81RlmXkQ/c6D24EVTdeupGFXg5wNL07ppGCAwjUXh094PQcxXrvxhOfTr6vhnF/lUBnmUKROQkfEepTzOUwcmn3ruvpRBqPULyghqrg3pr9vRIG5tY5ER7o8NIMO5LEzDjRhzGi4O0Rjk/tOfRrnaEG1RDjFhJKGQyFmOH0Q4HWigEZ/4/VohrYXSVNlVZAO4ApSb4yfyAwZLuMwbUsDtCQ2bjbdd/YiHPM+M+17z3rU3kH+pqiogQ0fnVlb0BarIIe2vi5e4LKLAcyX+dfehzsJ1u1XH/k69iE07OPf77RdAwHEH4l3j8karelsUwhdzTNdrZp4FvoCG0SIVomFIhy7CtCrXMu8JFBIyN9kIw9rgE98+GdukqVfBgPFxinbaaTJ01smM3ma9y1yOsOzmu3w8/2aGIA==
  template:
    metadata:
      labels:
        app.kubernetes.io/name: argocd-secret
        app.kubernetes.io/part-of: argocd
      name: argocd-secret
      namespace: argocd
