apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
data:
  url: https://argocd.cloud.feddema.dev
  statusbadge.enabled: "true"
  
  users.anonymous.enabled: "false"
  users.session.duration: "24h"

  kustomize.enabled: "true"
  jsonnet.enabled: "true"
  helm.enabled: "true"
  
  helm.valuesFileSchemes: http, https

  admin.enabled: "false"
  accounts.alice.enabled: "false"

  timeout.reconciliation: 180s
  cluster.inClusterEnabled: "true"

  server.rbac.log.enforce.enable: "false"

  exec.enabled: "true"
  exec.shells: "bash,sh,powershell,cmd"
  
  oidc.tls.insecure.skip.verify: "false"
  oidc.config: |
    name: Keycloak
    issuer: https://auth.cloud.feddema.dev/realms/master
    clientID: argocd
    clientSecret: $oidc.keycloak.clientSecret
    requestedScopes: ["openid", "profile", "email", "groups"]
