apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-dns
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io

spec:
  project: default
  source:
    chart: external-dns
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 6.5.5

    helm:
      values: |
        sources:
          - ingress

        provider: cloudflare

        containerPorts:
          http: 7979
          
        combineFQDNAnnotation: false
        ignoreHostnameAnnotation: false
        publishInternalServices: false
        publishHostIP: false
        serviceTypeFilter: []

        cloudflare:
          secretName: "cloudflare-api-token"
          proxied: false

        domainFilters: []
        excludeDomains: []
        regexDomainFilter: ""
        regexDomainExclusion: ""
        zoneNameFilters: []
        zoneIdFilters: []
        annotationFilter: ""
        labelFilter: ""

        dryRun: false
        triggerLoopOnEvent: false
        interval: "1m"
        logLevel: info
        logFormat: text
        policy: sync

        registry: "txt"
        txtPrefix: ""
        txtSuffix: ""
        txtOwnerId: ""
        forceTxtOwnerId: false
        replicaCount: 1

        crd:
          create: false
          
        service:
          enabled: false
          type: ClusterIP
          ports:
            http: 7979
            
        serviceAccount:
          create: true
          automountServiceAccountToken: true

        rbac:
          create: true
          clusterRole: true
          apiVersion: v1
          pspEnabled: false

        podSecurityContext:
          enabled: true
          fsGroup: 1001
          runAsUser: 1001
          
        resources:
          limits:
            cpu: 50m
            memory: 50Mi
          requests:
            cpu: 10m
            memory: 30Mi

        livenessProbe:
          enabled: true
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 2
          successThreshold: 1
        readinessProbe:
          enabled: true
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 6
          successThreshold: 1
        startupProbe:
          enabled: true
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 6
          successThreshold: 1

        metrics:
          enabled: false
          serviceMonitor:
            enabled: false

  destination:
    server: https://kubernetes.default.svc
    namespace: external-dns

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 5
        maxDuration: 10m

