apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-token
  namespace: external-dns
spec:
  encryptedData:
    cloudflare_api_token: AgB5mVoaCG0B4Poihy4FfgwpLEXU0qdMkvyV7G6T/hUFCv9on0H4OHySFj0JszCe8kLyOXX8yQCmqKYIlBjcL2I+K8wse4CKLNEV69p+dLtLuRteamYm3rgTc6v7vM0noPz8KLHgrh3dH/pG7r2SU6UvANF/+M4t2lAnHLMzj5kwAAdfQ7NVEaINF6QFeTkexZePRV3lhC226ByaTEpezsQn7LUZ4DFhMzp7RXZW295LSKcvYyBOxHsNkZNldjxPw8B/DdRk2Yc+ALSAlkYboRKrnax8rRxYDoc9HqIvDwlThkzo2DaY2PbpGl2OY6rNQX5KSGl7zJ2oo/pNCMJ63stBzkJiGaR34d0YuJnf8Ut5YAIztYrJOHuszUGRTwF4srSkvp6vFcZ/WDLWQ12dgMcNVI19jiEDFsFzKCjzs357qRZDYrB2KRdlTZ5e2DQI2B7nC8crGllk8XAspB8ME0SLX92hudwB2DVAPG0doe4k/7Q54qF4VMWs8gLdPXFGWdni0XYRMPaxJMyQm8ACDNgQgGEYlLa6HuOEmjX/HO727Ak7+x0OFGYg1TKIgQpg9yra8F3PiGO/ernvT4UYF1RE8YuSNGuBW/NoXi7nhAYKdC6KRhrftUEk2jq8myfV/o17E+h5zxC1BnhSg9/RY7fOyj8ncII9RzudVX3zYuPEols9tcUmAbfVOcV/WwbruYVl3g87WuYft1j31DSdx4VX6JIG71qhuLlpNsBBkJ524IBcoGv2TbbO
  template:
    metadata:
      name: cloudflare-api-token
      namespace: external-dns
    type: Opaque
