apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-token
  namespace: external-dns
spec:
  encryptedData:
    cloudflare_api_token: AgABR3NwN8kVnF92zVktZbi9CY6iuJp9uWx0QDaYw0kWgTTSn5EaG7+unhF31bAxMh8MiYPWCe+JrYMHgpYfGudf+5yK4TAtKVetd/3aUUj+szl5RcOi2XqHY/MGk9p1YlQmkHKccPe0HYL6pyTLAAi2RxKbGybA9bUiS/RVshBCOBu9v2I8NYwGhVcrFRmuZaWNi7s7WjMe7MmfO+SUjL37/8Trs83nMLuhvwuOXVpwIbD8Uood7Khy6UB8+BqeVo1FFtQ7Fr/9k4ekTbnnUDPRLCL5PqfIkKsfUesTBF854+51ZN1tF5YZWAsLXcp4jfE3s8Gy6umJ2ZbGLUyt+c98alc8oHKUgNk0Pt6PLy75ARJ8yaTMe42yA88+9mzCr5hT9ixuPHr116UM8SZLAu8RJTNPWyhcF59ZEnIjD3hSOrKCCcnFFqm/WcP+QMbSa1OaxquebPygv0wNYQxb7iyUQTNWMb1DaomNjKuTx/AnO2MChayDFKJkgp8pfaW37InG/HSMd4FSr0qmXrsSIhuW+E70kdjgu1sHGFX52bpvlgUs/WYdkhe/0ph+Ybv2FpAI4IS6Yp2r3MemaFzkI0k7F2sWTj5WDiWhY0LxhqKoNEIudnJJQA0apDPz4J68aVGnNZ6tCaRQDv3HVmUq/31v12SY6z2mu1HSC3+WgEaUHvu46F08D+MnAWzChn6vYwG/1MezGZxGAVOO4ETQ1AGdYV69u18RVyMookbUNWsMaLO5ajKEkHBm
  template:
    metadata:
      name: cloudflare-api-token
      namespace: external-dns
    type: Opaque
