apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-dns-application
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io

spec:
  project: default
  source:
    repoURL: https://github.com/florisfeddema/cloud-gitops.git
    targetRevision: HEAD
    path: base/external-dns

    directory:
      recurse: false

  destination:
    server: https://kubernetes.default.svc
    namespace: external-dns

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 5
        maxDuration: 10m

