apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgresql
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io

spec:
  project: no-sync
  source:
    chart: postgresql
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 11.6.16

    helm:
      values: |
        diagnosticMode:
          enabled: false

        image:
          tag: 14.4.0-debian-11-r9
          debug: false

        auth:
          enablePostgresUser: true
          replicationUsername: repl_user
          existingSecret: postgresql-credentials
          usePasswordFiles: true

        architecture: standalone

        containerPorts:
          postgresql: 5432

        ldap:
          enabled: false

        postgresqlDataDir: /bitnami/postgresql/data
        shmVolume:
          enabled: true

        tls:
          enabled: false


        primary:
          standby:
            enabled: false

          livenessProbe:
            enabled: true
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 6
            successThreshold: 1

          readinessProbe:
            enabled: true
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 6
            successThreshold: 1

          startupProbe:
            enabled: false

          resources:
            limits:
              memory: 256Mi
              cpu: 250m
            requests:
              memory: 128Mi
              cpu: 50m

          podSecurityContext:
            enabled: true
            fsGroup: 1001

          containerSecurityContext:
            enabled: true
            runAsUser: 1001

          service:
            ports:
              postgresql: 5432

          persistence:
            enabled: true
            mountPath: /bitnami/postgresql

            accessModes:
              - ReadWriteOnce

            size: 64Gi

        networkPolicy:
          enabled: false

          metrics:
            enabled: false

          ingressRules:
            primaryAccessOnlyFrom:
              enabled: false
            readReplicasAccessOnlyFrom:
              enabled: false

          egressRules:
            denyConnectionsToExternal: false

        volumePermissions:
          enabled: false

        serviceAccount:
          create: false

        rbac:
          create: false

        psp:
          create: false

        metrics:
          enabled: false

  destination:
    server: https://kubernetes.default.svc
    namespace: postgresql

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 5
        maxDuration: 10m

