apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgresql-credentials
  namespace: postgresql
spec:
  encryptedData:
    postgres-password: AgBMiMqtKKA4Hv+of7DzOFjDSrz3WWf0EENqVApIttr2xuUDj6BRJ2DxxWUizBJsmlYK2mJ7jTyEsxDf3SlacHDf2X+nl+EsidCNI2R4R74MMByagfknHKzY7BToL1sSk3uOlnJfLmXS3jg5ktdtRpki1ZiwYZtBgkX6A7njAcw/N5uLjQv3Y8cfLwMfgeZCkJ+6ssqOtHnILMLX27Ae2Tsf3Tw7V1nAkHc/U5YO+p7UcLbZ4omR2B00D3y035Xd4rfxNUP/SB5t/CTtsVDsVW++9t3/79hzcF6h00y5DKWXIyJZOuNg0y1sxOqrywR3bSteE9E/c8ewLlSGRXWtZt6unnddt3Ev2VTqqYy7vH1q83hzM/zUup0an2Rl9kNW+CSdinovx9+Rx2ejdijbDVkq5bRW19mvAXy9BaP5h1BEMN8iczI0l4kRZyRB6ze3maaEN5sATqwatR/e/NTSfIdRMVD9GufuodqivflHuGnuo3pCWTRCjbPCoPpwpYz1Rc9Ocn2JHVCP18Vc7BZ38h3kP44iX32Rk37CljHpmGtgMUskAjPbfuhC5gRL06xnm+Q33plLXRyvC7cHbGcGVkTJFOt9vVIerIYZLhRtrzvfBljfUeoOj1e/Csy4TBLQekjm842Jp1xwpccTRmTYQOM6VVEwe8eSBDfXHeYLFcRTRPgxcd+Wc+Ru9I7E/cyUtfMUhjRvOKb+toIzRL9PWdVvInjheqVRAp1tgPt+9hp+Ow==
    replication-password: AgCN5NwffS4sP9tL4PSMEch/A/q3BE9qYTFlVZe/lrfRPpHYd4t+nUitt38ttHgquUiv5faPMtId2lBWTvVhYzhfQD3yQJzRgecDdbdA9vcMLkDTajcy5uDKD2KU2mzMsCcHDPHHaSSxff/UM5vHRxiiNmwhZUriTILe9lns+AitN7XqjvxsGqCEJlpHhGfJq8cXwH+ZKe0Yj4wFTAx/qXfV8iP/+rllEaZdbS29CI+K8f+1RHFh3Hml3S+fmqWJanANLkgXOSUH4qR8HlJLXqFrdSGbKAcHmWhT6JtZeVOWNG0uwlRUGLTyXi0TkaJp5l8VNrKtkatKcabizIJvjOrjP7087/e73B0waV8MkZUVIwQSo58IrKnZmQ4Ynn1//yaDG86d6ARPW0+tkN6Ea2/3veLWcNZMD5fzGN7Axb80IhG7cDOEisvrTv4LOB7HckNMqm9yvMuyCIHKeRvArOivgXSj4Y73WCeze65Qlp/mwwGnRuHoWnD24YCsZSIz86d7ccblNn8HmSKHaJysUfJIWNrKfMo//Ca1g6Hz2XSPMja28FHTumHN7AzL9PqfzSfaatM9VyLmIYulSp6l0cf6fvDrZxblgXh5aa0BAR91f+dvoLdPyEtBcFQnaW7JAxpHVA96j2C4pyCSl73q2d9JTI0sOmU3xr15HezsF0UlGhVxzEnGdDEBexbqMNCQ8KmQQ1ti3gyFa5ygS1SeMob5QO97GH/PCY73wVy1ndMMnw==
  template:
    metadata:
      name: postgresql-credentials
      namespace: postgresql
    type: Opaque

